format = """
[î‚°](bg:#55887c fg:#55887c)\
$username\
[î‚°](bg:#8a9647 fg:#55887c)\
$directory\
[î‚°](fg:#8a9647 bg:#b27d29)\
$git_branch\
$git_status\
[î‚° ](fg:#b27d29)\
[ ]()
"""
# [â•­â”€](#D4BE98)[î‚¶](#55887c)\
# [â•°â”€ ](#D4BE98)
add_newline = false
right_format = """$pipestatus $status"""

[status]
symbol = "âœ– "
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
signal_symbol = "âš¡"
style = "bold red"
recognize_signal_code = true
disabled = false
pipestatus = true
format = "[$symbol$status]($style) "

[username]
show_always = true
style_user = "bg:#55887c fg:#282828"
style_root = "bg:#55887c fg:#282828"
format = '[$user ]($style)'

[directory]
style = "bg:#8a9647 fg:#282828"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "îœ¥"
style = "bg:#b27d29 fg:#282828"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#b27d29 fg:#282828"
format = '[$all_status$ahead_behind]($style)'

# (bg:#b27d29)
#Next color if needed: #c1537?
