format = """
[î‚°](bg:#81a1c1 fg:#81a1c1)\
$username\
[î‚°](bg:#a3be8c fg:#81a1c1)\
$directory\
[î‚°](fg:#a3be8c bg:#d79784)\
$git_branch\
$git_status\
[î‚° ](fg:#d79784)\
[ ]()
"""
# [â•­â”€](#D4BE98)[î‚¶](#81a1c1)\
# [â•°â”€ ](#D4BE98)
add_newline = false
right_format = """$pipestatus $status"""

[status]
symbol = "âœ– "
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
signal_symbol = "âš¡"
style = "bold red"
recognize_signal_code = true
disabled = false
pipestatus = true
format = "[$symbol$status]($style) "

[username]
show_always = true
style_user = "bg:#81a1c1 fg:#242923"
style_root = "bg:#81a1c1 fg:#242923"
format = '[$user ]($style)'

[directory]
style = "bg:#a3be8c fg:#242923"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "îœ¥"
style = "bg:#d79784 fg:#242923"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d79784 fg:#242923"
format = '[$all_status$ahead_behind]($style)'

# (bg:#d79784)
#Next color if needed: #c1537?
