format = """
[î‚°](bg:#1c71d8 fg:#1c71d8)\
$username\
[î‚¼](bg:#2ec27e fg:#1c71d8)\
$directory\
[î‚¼](fg:#2ec27e bg:#ff7800)\
$git_branch\
$git_status\
[î‚° ](fg:#ff7800)\
[ ]()
"""
# [â•­â”€](#D4BE98)[î‚¶](#1c71d8)\
# [â•°â”€ ](#D4BE98)
add_newline = false
right_format = """$pipestatus $status"""

[status]
symbol = "âœ– "
not_executable_symbol = "ğŸš«"
not_found_symbol = "ğŸ”"
signal_symbol = "âš¡"
style = "bold red"
recognize_signal_code = true
disabled = false
pipestatus = true
format = "[$symbol$status]($style) "

[username]
show_always = true
style_user = "bg:#1c71d8 fg:#1d1d1d"
style_root = "bg:#1c71d8 fg:#1d1d1d"
format = '[$user ]($style)'

[directory]
style = "bg:#2ec27e fg:#1d1d1d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = "îœ¥"
style = "bg:#ff7800 fg:#1d1d1d"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ff7800 fg:#1d1d1d"
format = '[$all_status$ahead_behind]($style)'

# (bg:#ff7800)
#Next color if needed: #c1537?
